# Generated by Django 3.2.16 on 2024-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('is_avail', models.BooleanField()),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
