# Generated by Django 3.2.16 on 2024-02-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
